version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-apache
    container_name: php_apache_
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql_db_
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    #volumes:
      #- ./src/Config/Migrations/db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3006:80"
    networks:
      - app-network
    #depends_on:
      #- db  # Garante que o phpMyAdmin só inicie após o MySQL

networks:
  app-network:
    driver: bridge